In [1]:
import numpy as np
import scipy

In [2]:
data = [1.4943494992895578,0.5769536064715798,0.3149033083265545,1.269732163578519,0.2813366747955667,1.001479518497029,0.7021766654199879,2.243554270691174,1.4781938165307542,0.3298295025703022,1.061610363524014,0.8151904835943997,1.1050816804713457,3.380399241581187,1.345369208717488,3.622572495940986,0.8994948134045655,4.0468444208208005,0.21386373015755133,0.45252718286987076]

In [3]:
la = 2
a = 2
f = lambda x: la *np.power(-np.log(x), 1/a)

In [4]:
data = 2*np.random.weibull(2, 20)
data

array([0.54199787, 1.50922404, 2.18409044, 1.46121127, 2.3346654 ,
       5.35738224, 1.74972001, 1.47100769, 2.79869621, 2.20092446,
       1.57474238, 1.36454239, 1.75623056, 0.63274343, 3.68876069,
       0.32559848, 1.53851738, 0.97985547, 1.4004298 , 2.07786194])

In [5]:
d = 2 * data
d

array([ 1.08399574,  3.01844808,  4.36818088,  2.92242255,  4.66933081,
       10.71476449,  3.49944003,  2.94201537,  5.59739243,  4.40184892,
        3.14948476,  2.72908477,  3.51246111,  1.26548685,  7.37752139,
        0.65119696,  3.07703477,  1.95971095,  2.8008596 ,  4.15572389])

In [6]:
f(2)

C:\Users\fuerf\AppData\Local\Temp\ipykernel_2028\1743451294.py:3: RuntimeWarning: invalid value encountered in power
  f = lambda x: la *np.power(-np.log(x), 1/a)


nan

In [7]:
f(d)

C:\Users\fuerf\AppData\Local\Temp\ipykernel_2028\1743451294.py:3: RuntimeWarning: invalid value encountered in power
  f = lambda x: la *np.power(-np.log(x), 1/a)


array([     nan,      nan,      nan,      nan,      nan,      nan,
            nan,      nan,      nan,      nan,      nan,      nan,
            nan,      nan,      nan, 1.309875,      nan,      nan,
            nan,      nan])

In [8]:
np.power(2, 3)

8

In [9]:
d_22 = [0.7851163214901727,3.176465295448296,2.0436461244766355,0.7292763029798089,1.0116570138935275,1.0979162477584126,0.546531160795282,4.231846006435566,2.8815172278886383,1.762190546474031,2.8010921857901034,1.0161088338122055,1.5905643295373884,2.1283026189538523,2.4062004455607333,2.0728254814708054,3.2548374123564505,3.1678904571745456,2.5800108111032127,0.41861001196871234]

In [10]:
c, loc, scale = scipy.stats.weibull_min.fit(d_22)

In [11]:
k = 1/c
la = scale ** k

In [12]:
k

0.6419669442411073

In [13]:
la

1.4946855913140311

In [14]:
d_22 = scipy.stats.weibull_min.rvs(c=2, scale=2, size=20)
d_22 = [1.27130156, 1.73100356, 0.91877032, 1.15029063, 0.79690807,
       0.82320322, 1.73468943, 1.27893022, 1.63603186, 1.3315046 ,
       1.39260357, 2.66624242, 3.21606522, 0.88658399, 1.71932343,
       1.28004802, 2.76046916, 1.80980035, 3.14431371, 2.05362395]
# by julia this gets fitted to Weibull{Float64}(α=2.483992637042323, θ=1.9014217748275557)

In [15]:
c, loc, scale = scipy.stats.weibull_min.fit(d_22)
#d_22_t = np.power(d_22, )
la = 1/c
k = c
print(f"c={c} loc={loc} scale={scale}")
print(f"lambda={la} k={k}")

c=0.7059788852600504 loc=0.7969080699999999 scale=1.0457784901373914
lambda=1.41647295815603 k=0.7059788852600504


In [ ]:
c, loc, scale = scipy.stats.weibull_min.fit(d_22)
#d_22_t = np.power(d_22, )
k = 1/c
la = scale ** k
print(f"c={c} loc={loc} scale={scale}")
print(f"lambda={la} k={k}")

In [ ]:
d_jl (generiert)

In [36]:
scipy.stats.weibull_min.fit(scipy.stats.weibull_min.rvs(c=2, scale=2, size=20000))

(1.9823208539538093, 0.00026504308289985155, 1.9955926622676194)

In [37]:
k = 1/c
la = scale ** k